# Generated by Django 3.2.5 on 2021-07-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_alter_person_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/'),
        ),
    ]
